services:
  - type: web
    name: laravel-docker-app
    env: docker
    region: oregon  # または tokyo など希望のリージョン
    plan: free
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
        - .  # すべてを含める（必要に応じて調整）
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-twilight-unit-a1waa9ob-pooler.ap-southeast-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_s1CAzjOcnbH9
